export const COMMIT_KEYWORDS = Object.freeze({
  doc: Object.freeze(["doc:", "docs:", "documentation"]),
  feature: Object.freeze(["feat:", "feature:", "add:", "implement"]),
  fix: Object.freeze(["fix:", "bugfix:", "hotfix:"]),
  perf: Object.freeze(["perf:", "performance:", "optimize"]),
  refactor: Object.freeze(["refactor:", "cleanup:", "restructure"]),
  test: Object.freeze(["test:", "tests:"]),
  update: Object.freeze(["update:", "upgrade:"]),
});

export const CODING_EXTENSIONS = Object.freeze([
  ".asm",
  ".bash",
  ".c",
  ".clj",
  ".cpp",
  ".cs",
  ".dart",
  ".ex",
  ".exs",
  ".fs",
  ".go",
  ".h",
  ".hpp",
  ".hs",
  ".java",
  ".js",
  ".jsx",
  ".kt",
  ".lua",
  ".m",
  ".mm",
  ".php",
  ".pl",
  ".py",
  ".r",
  ".rb",
  ".rs",
  ".s",
  ".scala",
  ".sh",
  ".sql",
  ".swift",
  ".ts",
  ".tsx",
  ".vb",
]);
